### ISSUE TITLE
Should we archive this repo?

### ISSUE THREAD

**Issue by jdolitsky** [oci-playground/artifact-spec#6]
Should we move the types into the image-spec fork to more closely align with the upcoming PR submission?
cc @sajayantony @sudo-bmitch

**Comment by sudo-bmitch** [comment]
SGTM

**Comment by jdolitsky** [comment]
ok. will wait to do so until all the tooling has been moved over

**Comment by sajayantony** [comment]
+1 now that we are leaning towards an update to image-spec.

**Comment by sudo-bmitch** [comment]
Yes we should, archiving it now.
